# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
defaults: &defaults
  docker:
    - image: circleci/node:9


jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.0.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      # - run: yarn test
  
  publish-production:
    <<: *defaults
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: install
          command: yarn install
      - run:
          name: install expo client
          command: sudo yarn global add expo-cli
      - run:
          name: check the expo version
          command: expo --version
      - run:
          name: login expo
          command: expo --non-interactive login -u $EXPO_ACCOUNT -p $EXPO_PASSWORD 
      - run:
          name: publish to production
          command: expo publish --release-channel sandbox-production

  publish-staging:
    <<: *defaults
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: install
          command: yarn install
      - run:
          name: install expo client
          command: sudo yarn global add expo-cli
      - run:
          name: check the expo version
          command: expo --version
      - run:
          name: login expo
          command: expo --non-interactive login -u $EXPO_ACCOUNT -p $EXPO_PASSWORD
      - run:
          name: publish to production
          command: expo publish --release-channel sandbox-staging


workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      # - publish-staging:
      #     requires:
      #       - build
      #     filters:
      #       tags:
      #         ignore: /.*/
      #       branches:
      #         only: develop
      - publish-production:
          requires:
            - build
          filters:
            tags:
              only: /^release-v.*/
            branches:
              ignore: /.*/